<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PackageUniverse.Application\PackageUniverse.Application.csproj" />
        <ProjectReference Include="..\PackageUniverse.Core\PackageUniverse.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
    </ItemGroup>

</Project>
